assign2/jobseeker/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::get('/', array('as'=>'home', 'uses'=> 'JobController@index'));
Route::get('job/listAll', array('as' => 'job.listAll', 'uses' => 'JobController@listAll'));

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));

Route::get('about/about', array('as'=>'about.about', 'uses'=> 'HomeController@about'));

Route::resource('user', 'UserController');
Route::resource('job', 'JobController');
Route::resource('about', 'HomeController');
Route::resource('application', 'ApplicationController');

assign2/jobseeker/app/models/Job.php
<?php
use Carbon\Carbon;
class Job extends Eloquent{

  //rules for job table validation
  public static $rules = array(
    'job_title' => 'required',
    'job_desc' => 'required',
    //'user_id'  => 'required',
    'location' => 'required',
    'salary' => 'required|integer',
    'start_date' => 'required',
    'final_date' => 'required'
  );

  /*
   * one to many relationship between users and jobs
   * jobs only have one user(creator)
   * but they have many users applying ??????
   */
  public function user(){
    return $this->belongsTo('User');
  }
  public function application(){
    return $this->hasMany('Application');
  }



  public function getDates(){
    return array('created_at','updated_at', 'start_date', 'final_date');
  }

}

assign2/jobseeker/app/controllers/JobController.php
<?php

class JobController extends \BaseController {

  /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
  public function index()
  {
    //
    $jobs = Job::whereRaw('start_date > ?',array(new DateTime('10 May 2014')))->paginate(3);
    $now = new DateTime();
    return View::make('job.index', compact('jobs', 'now'));
  }
  /**
	 * Display a list of all jobs.
	 *
	 * @return Response
	 */
  public function listAll()
  {
    //
    $keyword = Input::get('keyword');
    $now = new DateTime();
    if (empty($keyword)) 
    {
      $jobs = Job::paginate(3);
      return View::make('job.listAll', array('jobs' => $jobs, 'keyword' => $keyword, 'now' => $now));
    }
    else
    {
      $jobs = Job::whereHas('user', function($q) use ($keyword)
                            {
                              return $q->whereRaw('industry like ?', array("%$keyword%"));
                            })       ->orWhereRaw('job_desc like ?', array("%$keyword%"))
        ->orWhereRaw('job_title like ?', array("%$keyword%"))
        ->orWhereRaw('location like ?', array("%$keyword%"))
        ->orWhereRaw('salary > ?', array($keyword))
        ->paginate(3);
      return View::make('job.listAll', array('jobs' => $jobs, 'keyword' => $keyword, 'now' => $now));
    }
  }

  /**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
  public function create()
  {
    //
    return View::make('job.create');
  }


  /**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
  public function store()
  {
    //
    $input = Input::all();
    $job = new Job();
    $v = Validator::make($input, Job::$rules);
    if ($v->passes())
    {
      $job->job_title = $input['job_title'];
      $job->user_id = $input['user_id'];
      $job->job_desc = $input['job_desc'];
      $job->location = $input['location'];
      $job->salary = $input['salary'];
      $job->start_date = $input['start_date'];
      $job->final_date = $input['final_date'];
      $job->save();
      return Redirect::route('job.show', $job->id);
    }
    else
    {
      // Show validation errors
      if ($job)
      {
        return Redirect::route('job.create', array('job' => $job))->withErrors($v);
      }
      else
      {
        return Redirect::route('job.create');
      }
    }
  }

  /**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function show($id)
  {
    //
    $jobs = Job::find($id);
    $now = new DateTime();
    $applications = $jobs->application;
    return View::make('job.show', compact('jobs', 'now', 'applications'));
  }


  /**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function edit($id)
  {
    //
    $jobs = Job::find($id);
    $now = new Dateime();
    return View::make('job.edit', compact('jobs', 'now'));
  }


  /**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function update($id)
  {
    //
    $jobs = Job::find($id);
    $input = Input::all();
    $v = Validator::make($input, Job::$rules);
    if ($v->passes())
    {
      $jobs->job_title = $input['job_title'];
      $jobs->job_desc = $input['job_desc'];
      $jobs->location = $input['location'];
      $jobs->salary = $input['salary'];
      $jobs->save();
      return Redirect::route('job.show', $jobs->id);
    }
    else
    {
      // Show validation errors
      return Redirect::route('job.edit', $jobs->id)->withErrors($v);
    }
  }


  /**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function destroy($id)
  {
    //
    $jobs = Job::find($id);
    $jobs->delete();
    return Redirect::route('job.index');
  }

}

assign2/jobseeker/app/views/job/create.blade.php
@extends('job.layout')

@section('content')
<img src="../images/logo.png" alt="Logo Oz Vacancies">
@stop

@section('content1')
  <div class="col-sm-9">
    <h1 id="heading">Create Job</h1>
    {{ Form::open(array('action' => 'JobController@store')) }}
    <br><p>
    {{ Form::label('job_title', 'Job Title:', array('class' => 'col-sm-3')) }}
    {{ Form::text('job_title') }}
    <p>{{$errors->first('job_title')}}
    <br><p>
    {{ Form::hidden('user_id', Auth::user()->id) }}
    {{ Form::label('job_desc', 'Job Description:', array('class' => 'col-sm-3')) }}
    {{ Form::text('job_desc') }}
    <p>{{$errors->first('job_desc')}}
    <br><p>
    {{ Form::label('location', 'Location:', array('class' => 'col-sm-3')) }}
    {{ Form::text('location') }}
    <p>{{$errors->first('location')}}
    <br><p>
    {{ Form::label('salary', 'Salary:', array('class' => 'col-sm-3')) }}
    {{ Form::text('salary') }}
    <p>{{$errors->first('salary')}}
    <br><p>
    {{ Form::label('start_date', 'Start Date:', array('class' => 'col-sm-3')) }}
    {{ Form::text('start_date', null, array('placeholder' => 'YYYY-mm-dd')) }}
    <p>{{$errors->first('start_date')}}
    <br><p>
    <br><p>
    {{ Form::label('final_date', 'Finish Date:', array('class' => 'col-sm-3')) }}
    {{ Form::text('final_date', null, array('placeholder' => 'YYYY-mm-dd')) }}
    <p>{{$errors->first('final_date')}}
    <br><p>
    {{ Form::submit('Create', array('class' => 'btn btn-success')) }}
    <br><p>
    {{ Form::close() }}
  </div>
@stop

assign2/jobseeker/app/views/job/edit.blade.php
@extends('job.layout')

@section('content')
  <img src="../../images/logo.png" alt="Logo Oz Vacancies">
@stop

@section('content1')
  <div class="col-sm-9">
    <h1 id="heading">Edit Job</h1>
    <br>
      {{ Form::model($job, array('method' => 'PUT', 'route' =>array('job.update', $job->id))) }}
      {{ Form::label('job_title', 'Job Title:') }}
      {{ Form::text('job_title') }}
      {{ $errors->first('job_title') }}
    <p>
      {{ Form::label('job_desc', 'Job Description:') }}
      {{ Form::text('job_desc') }}
      {{ $errors->first('job_desc') }}
    <p>
      {{ Form::label('location', 'Location:') }}
      {{ Form::text('location') }}
      {{ $errors->first('location') }}
    <p>
      {{ Form::label('salary', 'Salary:') }}
      {{ Form::text('salary') }}
      {{ $errors->first('salary') }}
    <p>
      {{ Form::submit('Update') }}
      {{ Form::close() }}
  </div>
@stop

assign2/jobseeker/app/views/job/index.blade.php
@extends('job.layout')

@section('content')
  <img src="images/logo.png" alt="Logo Oz Vacancies">
  <h3 class="list-heading">Recently Added</h3>
    <ul>
      @foreach ($jobs as $job)
        @if ($job->final_date > $now)
          <li>{{link_to_route('job.show',$job->job_title, array($job->id)) }}</li>
        @endif
      @endforeach
    </ul>
    {{ $jobs->links()}}
    <p>{{ link_to_route('job.listAll','See all Jobs') }}
@stop

@section('content1')
  <div class="col-sm-9">
    <br><img src="images/jobwanted.jpg" alt="Job Wanted Picture">
    <h3 id="heading"> Search for a Job... </h3>
    <br>
    <div id="content">
      <p id="search">I'd like a job in:<p>
      {{ Form::open(array('method' => 'GET', 'action' => 'JobController@listAll')); }}
      {{ Form::text('keyword', null, array('placeholder' => 'search by keyword')); }}
      {{ Form::submit('Search', array('class' => 'btn btn-success')); }}
      {{ Form::close(); }}
      <p>E.g Search for position name, keyword in description, industry, location or minimum salary </p>
    </div>
 </div>
@stop

assign2/jobseeker/app/views/job/layout.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Oz Vacancies</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!-- Add custom CSS here -->
    {{ HTML::style('styles/style.css')}}
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=""></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li>{{link_to_route('job.index', 'Home' )}}</li>
            <li><a href=""></a></li>
            <li>{{link_to_route('about.about', 'About' )}}</li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            @if (Auth::check())
            <li>{{ link_to_route('user.logout', 'Logout (' . Auth::user()->name . ')') }}</li>
            @endif
          </ul>
        </div>
      </div>
    </div>
    <div id="main-body" class="container">
      <div class="row">
        <div class="col-sm-3">
          <div class="list-group">
            @yield('content')
          </div>
        </div>
        <div class="col-sm-9">
           @if (!Auth::check())
           <div class="login-form">
              {{ Form::open(array('action' => 'UserController@login')); }}
              {{ Form::text('username', null, array('class' => 'input-small', 'placeholder' => 'Email')); }}
              {{ Form::password('password', array('class' => 'input-small', 'placeholder' => 'Password')); }}
              {{ Form::submit('Sign in', array('class' => 'btn btn-danger')); }}
              {{ Form::close(); }}
              {{ Form::open(array('action' => 'UserController@create')); }}
              <p>{{link_to_route('user.create', 'or Register here',['category' => 1])}}
              <p>{{$errors->first('username')}}
              <p>{{$errors->first('password')}}
              {{ Form::close(); }}
          </div>
          <br>
          <br>
          <br>
          <br>
          {{link_to_route('user.create', 'Employers', ['category' => 2], array('class' => 'btn btn-primary')) }}
          <p id="employer-heading">Employers, Please register here:</p>
          @else
          <p><br> {{link_to_route('user.show', 'View Profile', ['id' => Auth::user()->id], array('class' => 'btn btn-primary')) }}
          @endif
          @yield('content1') 
          <br>
          <br>
          <br>
          <br>  
        </div>
        <footer>
          Angela King s2620368<br>
          2503ICT Web Programming Assignment 2
        </footer> 
      </div>
    </div>
  </body>
</html>

assign2/jobseeker/app/views/job/listAll.blade.php
@extends('job.layout')

@section('content')
  <img src="../images/logo.png" alt="Logo Oz Vacancies">
@stop

@section('content1')
  <h3 id="heading">All Jobs</h3>
    @if ($keyword != null)
      <p> Search results for "{{{$keyword}}}"</p>
    @endif
    @if (count($jobs) == 0)
      <p>Sorry, no jobs found matching that criteria</p>
    @else
      <ul>
        @foreach ($jobs as $job)
          @if ($job->final_date > $now)
            <li>{{link_to_route('job.show',$job->job_title, array($job->id)) }}</li>
          @endif
        @endforeach
     </ul>
    {{ $jobs->links()}}
    <br>
    <div id="content">
      <p id="search">Search Again:<p>
        {{ Form::open(array('method' => 'GET', 'action' => 'JobController@listAll')); }}
        {{ Form::text('keyword', null, array('placeholder' => 'search by keyword')); }}
        {{ Form::submit('Search', array('class' => 'btn btn-success')); }}
        {{ Form::close(); }}
        <p>E.g Search for position name, keyword in description, industry, location or minimum salary </p>
    </div>
  @endif
@stop

assign2/jobseeker/app/views/job/show.blade.php
@extends('job.layout')

@section('content')
  <img src="../images/logo.png" alt="Logo Oz Vacancies">
  @if((Auth::check()) and ((Auth::user()->category) == 2))
    <p>{{ link_to_route('job.create','Add new Job') }}
  @endif
@stop

@section('content1')
  <div class="col-sm-9">
    <h1 id="heading">Vacancy for "{{{$jobs->job_title}}}"</h1>
    <img src="{{ asset($jobs->user->profilePic->url('thumb')) }}">
    <br> 
    <dl>
        <dt id="heading">Employer:</dt>
        <dd>{{{ $jobs->user->name}}}</dd>
        <dt id="heading">Job Description:</dt>
        <dd>{{{$jobs->job_desc}}}</dd>
        <dt id="heading">Location:</dt>
        <dd>{{{$jobs->location}}}</dd>
        <dt id="heading">Salary:</dt>
        <dd>{{{$jobs->salary}}}</dd>
        <dt id="heading">Start Date:</dt>
        <dd>{{{ date("d.m.Y",strtotime($jobs->start_date)) }}}</dd>
        <dt id="heading">End Date:</dt>
        <dd>{{{ date("d.m.Y",strtotime($jobs->final_date)) }}}</dd>
        <dt id="heading">Days left to Apply:</dt>
        <dd>{{{$jobs->final_date->diff($now)->days}}}</dd>
     </dl> 
      @if (Auth::check())
        @if ((Auth::user()->category) == 1)    
          @foreach ($applications as $application)
            <li>{{link_to_route('application.show', $application->userName, array($application->id)) }}</li>
            <p>Sorry you've already applied for this job</p>
          @endforeach
          @if ($now > $jobs->final_date)
            <p> Sorry, applications have now closed
          @else
            <p>{{link_to_route('application.create', 'Apply Now', ['id' => $jobs->id], array('class' => 'btn btn-primary')) }}</p>
          @endif
        @elseif ((Auth::user()->id) == ($jobs->user_id))
        <p>{{link_to_route('job.edit', 'Edit', array($jobs->id)) }} </p>
        <p>{{link_to_route('job.index', 'Home' )}}</p>
        <p>
        {{ Form::open(array('method' => 'DELETE', 'route' =>array('job.destroy', $jobs->id))) }}
        {{ Form::submit('Delete', array('class' => 'btn btn-warning')) }}
        {{ Form::close() }} 
        <br>
        <p> You have received the following applications for this job:</p>
        <ul>
          @foreach ($applications as $application)
            <li>{{link_to_route('application.show', $application->userName, array($application->id)) }}</li>
          @endforeach
        <ul>
        @endif
      @else
          <p id="heading">please log in or register to apply</p>
      @endif
  </div>
@stop