assign2/jobseeker/app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/


Route::get('/', array('as'=>'home', 'uses'=> 'JobController@index'));
Route::get('job/listAll', array('as' => 'job.listAll', 'uses' => 'JobController@listAll'));

Route::post('user/login', array('as' => 'user.login', 'uses' => 'UserController@login'));
Route::get('user/logout', array('as' => 'user.logout', 'uses' => 'UserController@logout'));

Route::get('about/about', array('as'=>'about.about', 'uses'=> 'HomeController@about'));

Route::resource('user', 'UserController');
Route::resource('job', 'JobController');
Route::resource('about', 'HomeController');
Route::resource('application', 'ApplicationController');

assign2/jobseeker/app/models/User.php
<?php

use Illuminate\Auth\UserInterface;
use Illuminate\Auth\Reminders\RemindableInterface;

class User extends Eloquent implements UserInterface, RemindableInterface {
  /*
   * one to many relationship between users and jobs
   * users have many jobs
   */
  public function jobs(){
    return $this->hasMany('Job');
  }
  public function applications(){
    return $this->hasMany('Application');
  }
  public function getDates(){
    return array('created_at','updated_at', 'start_date', 'final_date');
  }
  /**
	 * The database table used by the model.
	 *
	 * @var string
	 */
  protected $table = 'users';

  /**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
  protected $hidden = array('password');

  /**
	 * Rules for validation
	 * Create and login
	 */
  public static $create_rules = array(
    'username' => 'required|unique:users',
    'password' => 'required',
    'name' => 'required'
  );
  public static $login_rules = array(
    'username' => 'required',
    'password' => 'required|confirmed'
  );

  /*
  * for images
  *
  */
  use Codesleeve\Stapler\Stapler;

  public function __construct(array $attributes = array()) {
    $this->hasAttachedFile('profilePic', [
      'styles' => [
        'medium' => '300x300',
        'thumb' => '100x100'
      ]
    ]);

    parent::__construct($attributes);
  }

  /**
	 * Get the unique identifier for the user.
	 *
	 * @return mixed
	 */
  public function getAuthIdentifier()
  {
    return $this->getKey();
  }

  /**
	 * Get the password for the user.
	 *
	 * @return string
	 */
  public function getAuthPassword()
  {
    return $this->password;
  }

  /**
	 * Get the token value for the "remember me" session.
	 *
	 * @return string
	 */
  public function getRememberToken()
  {
    return $this->remember_token;
  }

  /**
	 * Set the token value for the "remember me" session.
	 *
	 * @param  string  $value
	 * @return void
	 */
  public function setRememberToken($value)
  {
    $this->remember_token = $value;
  }

  /**
	 * Get the column name for the "remember me" token.
	 *
	 * @return string
	 */
  public function getRememberTokenName()
  {
    return 'remember_token';
  }

  /**
	 * Get the e-mail address where password reminders are sent.
	 *
	 * @return string
	 */
  public function getReminderEmail()
  {
    return $this->email;
  }

}

assign2/jobseeker/app/controllers/UserController.php
<?php

class UserController extends \BaseController {

  /**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
  public function index()
  {
    //
  }


  /**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
  public function create()
  {
    //
    $input = Input::all();
    $category = $input['category'];
    return View::make('user.create', compact('category'));
  }


  /**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
  public function store()
  {
    //
    $input = Input::all();
    $category = $input['category'];
    $v = Validator::make($input, User::$create_rules);
    if ($v->passes())
    {
      $password = $input['password'];
      $encrypted = Hash::make($password);
      $user = new User;
      $user->username = $input['username'];
      $user->password = $encrypted;
      $user->name = $input['name'];
      $user->category = $input['category'];
      $user->email = $input['username'];
      $user->phone = $input['phone'];
      $user->industry = $input['industry'];
      $user->profilePic = $input['profilePic'];
      $user->description = $input['description'];
      $user->remember_token = "default"; 
      $user->save();

      return Redirect::route('user.login');
    }
    else
    {
      // Show validation errors
      return Redirect::route('user.create', compact('user', 'category'))->withErrors($v);
    }
  }
  /**
	 * login in function.
	 *
	 * @return Response
	 */
  public function login()
  {
    //
    $input = Input::all();
    $username = $input['username'];
    $password = $input['password'];
    $v = Validator::make($input, User::$login_rules);
    if (Auth::attempt(compact('username', 'password'))){
      return Redirect::to(URL::previous());
    }
    else
      return Redirect::route('job.index')->withErrors($v);

  }
  /**
	 * logout function.
	 *
	 * @return Response
	 */
  public function logout()
  {
    //
    Auth::logout();
    return Redirect::route('job.index');
  }



  /**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function show($id)
  {
    //
    $user = User::find($id);
    $jobs = $user->jobs;
    $applications = $user->applications;
    return View::make('user.show', compact('user', 'applications', 'jobs'));

  }


  /**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function edit($id)
  {
    //
    $user = User::find($id);
    return View::make('user.edit', compact('user'));
  }


  /**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function update($id)
  {
    //
    $user = User::find($id);
    $input = Input::all();
    $user->name = $input['name'];
    $user->description = $input['description'];
    $user->phone = $input['phone'];
    $user->profilePic = $input['profilePic'];
    $user->save();
    return Redirect::route('user.show', $user->id);
  }




  /**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
  public function destroy($id)
  {
    //
    $users = User::find($id);
    $users->delete();
    return Redirect::route('job.index');
  }


}

assign2/jobseeker/app/views/user/create.blade.php
@extends('job.layout')

@section('content')
  <img src="../images/logo.png" alt="Logo Oz Vacancies">
@stop

@section('content1')
<div class="col-sm-9">
    @if($category == 2)
      <h1 id="heading">New Employer page</h1>
      <br>
      <p>{{ Form::open(array('route' => 'user.store', 'files' => true)) }}
      <p>{{ Form::label('username', 'Username:', array('class' => 'col-sm-4')) }}
      <p>{{ Form::text('username', null, array('class' => 'input-small', 'placeholder' => 'Email')) }}
      <p>{{$errors->first('username')}}
      <p>{{ Form::label('password', 'Password:', array('class' => 'col-sm-4')) }}
      <p>{{ Form::password('password', array('class' => 'input-small', 'placeholder' => 'Password')) }}
      <p>{{$errors->first('password') }}
      {{ Form::hidden('category', 2) }}
      <p>{{ Form::label('name', 'Name:', array('class' => 'col-sm-4')) }}
      <p>{{ Form::text('name') }}
      <p>{{$errors->first('name') }}
      <p>{{ Form::label('description', 'Company Description:', array('class' => 'col-sm-4')) }}
      <p>{{ Form::textarea('description') }}
      <p>{{ Form::label('industry', 'Industry', array('class' => 'col-sm-4')) }}
      <p>{{ Form::text('industry') }}
      <p>{{ Form::label('phone', 'Phone Number:', array('class' => 'col-sm-4')) }}
      <p>{{ Form::text('phone') }}
      <p>{{$errors->first('phone') }}
      <br>
      <p>{{ Form::label('profilePic', 'Upload your Company Logo:') }}
      <p>{{ Form::file('profilePic') }}
      <br>
      <p>{{ Form::submit('Create Account', array('class' => 'btn btn-info')) }}
      {{ Form::close() }}
    @else
      <h1 id="heading">New Job Seeker page</h1>
      <br>
      <p>{{ Form::open(array('route' => 'user.store', 'files' => true)) }}
      <p>{{ Form::label('username', 'Username:', array('class' => 'col-sm-3')) }}
      <p>{{ Form::text('username', null, array('class' => 'input-small', 'placeholder' => 'Email')) }}
      <p>{{$errors->first('username')}}
      <p>{{ Form::label('password', 'Password:', array('class' => 'col-sm-3')) }}
      <p>{{ Form::password('password', array('class' => 'input-small', 'placeholder' => 'Password')) }}
      <p>{{$errors->first('password') }}
      <p>{{ Form::hidden('category', 1) }}
      <p>{{ Form::hidden('industry', null) }}
      <p>{{ Form::label('name', 'Name:', array('class' => 'col-sm-3')) }}
      <p>{{ Form::text('name') }}
      <p>{{$errors->first('name') }}
      <p>{{ Form::label('description', 'About You:', array('class' => 'col-sm-3')) }}
      <p>{{ Form::textarea('description') }}
      <br><p>
      <p>{{ Form::label('phone', 'Phone Number:', array('class' => 'col-sm-3')) }}
      <p>{{ Form::text('phone') }}
      <p>{{$errors->first('phone') }}
      <p>{{ Form::label('profilePic', 'Upload your Profile Picture:') }}
      {{ Form::file('profilePic') }}
      <br><p>
      <p>{{ Form::submit('Create Account', array('class' => 'btn btn-info')) }}
      {{ Form::close() }}
    @endif
  </div>
@stop

assign2/jobseeker/app/views/user/edit.blade.php
@extends('job.layout')

@section('content')
  <img src="../../images/logo.png" alt="Logo Oz Vacancies">
@stop

@section('content1')
  <div class="col-sm-9">
  <h1 id="heading">Edit Profile</h1>
    {{ Form::model($user, array('method' => 'PUT',  'route' => array('user.update', $user->id),'files' => true)) }}
  <p>'Hi {{ Auth::user()->name }}, please update your details:'  </p>
  <br>
    {{ Form::label('name', 'Name:') }}
    {{ Form::text('name') }}
  <p>
    {{ Form::label('description', 'Description:') }}
    {{ Form::text('description') }}
  <p>
    {{ Form::label('phone', 'Phone:') }}
    {{ Form::text('phone') }}
    {{ $errors->first('location') }}
  <p>
    {{ Form::label('profilePic', 'Upload your Company Logo:') }}
    {{ Form::file('profilePic') }}
  <p>
    {{ Form::submit('Update', array('class' => 'btn btn-success')) }}
    {{ Form::close() }}
</div>
@stop

assign2/jobseeker/app/views/user/show.blade.php
@extends('job.layout')

@section('content')
  <img src="../images/logo.png" alt="Logo Oz Vacancies">
  @if($user->category == 2)
  <p>{{ link_to_route('job.create','Add new Job') }}
  @endif
@stop

@section('content1')
  <br>
  <h1 id="heading">Profile for "{{{$user->name}}}"</h1>
  <br> 
  <dl>
    <dt id="heading">Email:</dt>
    <dd>{{{$user->email}}}</dd>
    <dt id="heading">Phone: </dt>
    <dd>{{{$user->phone}}}</dd>
    <dt id="heading">About Us:</dt>
    <dd>{{{$user->description}}}</dd>
    <dt id="heading">Profile Picture:</dt>
    <dd><img src="{{ asset($user->profilePic->url('thumb')) }}"></dd>
  </dl> 
  <br>
  <br>
  <p>{{link_to_route('user.edit', 'Update Profile', array($user->id)) }} </p>
  <br>
    {{ Form::open(array('method' => 'DELETE', 'route' =>array('user.destroy', $user->id))) }}
    {{ Form::submit('Delete Account ', array('class' => 'btn btn-warning')) }}
    {{ Form::close() }}
    <br>
    @if ($user->category ==1)
      <p>You've applied for these jobs:</p>
        @if ($applications != null)  
          <ul>
            @foreach ($applications as $application)
              <li>{{link_to_route('application.show', $application->job->job_title, array($application->id)) }}</li>
            @endforeach
          </ul>
        @endif
    @else
      <p>Jobs you have listed:</p>
        <ul>
          @foreach ($jobs as $job)
        <li>{{link_to_route('job.show',$job->job_title, array($job->id)) }}</li>
      @endforeach
    </ul>
  @endif
@stop